ALTER TABLE sessions DROP CONSTRAINT fk_sessions_user_id;


DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL
);

DROP TABLE IF EXISTS sessions;
CREATE TABLE IF NOT EXISTS sessions (
	token VARCHAR(128) PRIMARY KEY,
	last_accessed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	user_id int NOT NULL,
	CONSTRAINT fk_sessions_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);