DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL,
	uploaded_audio VARCHAR(256) NULL,
	has_started_transcription BOOL NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS transcription_queues CASCADE;
CREATE TABLE IF NOT EXISTS transcription_queues (
	id serial PRIMARY KEY,
	is_being_processed BOOL NOT NULL DEFAULT FALSE,
	started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
	ended_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
	user_id int NOT NULL,
	CONSTRAINT fk_transcription_queue_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS sessions CASCADE;
CREATE TABLE IF NOT EXISTS sessions (
	token VARCHAR(128) PRIMARY KEY,
	last_accessed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	user_id int NOT NULL,
	CONSTRAINT fk_sessions_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);